1~10 카드
플레이어 4명
플레이어 덱 1장
데스크 덱 2장
진행자 덱 40 - 2 - 4

-게임 순서-
10 종류의 카드 중에 각각 4번의 중복을 허락하여 2장을 뽑는다. 
플레이어들에게 진행자 덱에서 각각 1장 씩 지급
데스크 덱 1장 오픈 후 플레이어들 순서대로 배팅 x 2
결과 확인 후 가넷 득실 따짐

순열 nPm = nCm * m!
조합 nCm = n*(n-1)*(n-2) / 3*2*1 = n! / m! / m! 
중복 순열 nπm = (n-1)!  // nCm * m!
n이 개수는 4배, 심볼이 그대로
심볼이 그대로이면 같은 카드니까 순서가 없어
n*4C2 * m! / 4Cm
40개 카드가 4종류야 2개 뽑았는데 둘 다 같은 심볼이 나올 확률 
같은 심볼 4개 중에 2개가 나올 확률
중복 조합 (n-1)!/

*순서가 없으면 중복 순열이 의미가 있나? 있긴한데 같은 숫자가 나온 개수를 나눠줘야돼 10개 중에 3개 뽑았는데 2개 중복 후 나열 3 3 1 
= 10P2 * 3(같은 심볼을 묶고 다른 심볼을 끼워 넣어, 2는 심볼 개수)
V3V3V = 3 총 개수를 나열하고 뽑힌 심볼 종류의 개수로 나눠 (3!/2)
뽑힌 심볼 종류의 개수(2)는 중복을 허락한 개수

**중복이 3개 있는 5개를 나열하는 경우의 수
12311 = 중복 허락 3
중복을 허락한 개수 3을 2, 3에 끼워 넣는 방법
= V2V3V
1이 3개 중복이니까 3자리 중에 1자리 선택, 2자리 선택, 3자리 선택하는 방법 // 동시아니지 가지 수 구하기니까
= 3C1 * 1 + 3C2 * 2 + 3C3 * 1 = 7 

중복이 되려면 동시에 같아야 중복이지!

**10개의 심볼이 3장씩 있을 때 5개를 뽑는 경우의 수 x 3장이 중복된 상황
= 10C5 / 3!(중복 허락 개수) / 10C3
= 10*9*8*7*6 / 10 * 9 * 8 * 6
= 10! / 5! / 5! / 3! = 3 2 7 = 42 = 7 * 6 = 7C2
= 10개의 심볼 / 5개 / 5개 나열 / 중복 3장

중복 조합 : 3C2 + 3C1 = nCm * nCn-m = 3의 제곱 = 3 * 3 = 9 

40개 카드가 4종류야 2개 뽑았는데 둘 다 같은 심볼이 나올 확률 
같은 심볼 4개 중에 2개가 나올 확률
10! / 2! * 2! / 2! =10 9 8 7 6 5 4 3 (가지 수)
40 * 39

40개 중에 같은거 2개 = 40 * 3 = 120 가지수
120 / 40 * 39 = 1/13

**조건부 확률 주의!


10C1 * 9P


스트레이트 = 1개가 정해지면 양 옆이 정해지니까 3개가 묶음

트리플 = 1개가 정해지면 나머지 2개가 같아

더블 = 1개가 정해지면 다른 하나는 같고 또 다른 하나는 무조건 달라


1번째 데스크 덱은 40개 중 1개를 뽑아
2번째 데스크 덱은 9개 중 1개 or  
2번째 데스크 덱은 10개 중 1개 * 3 or 

